### ISSUE TITLE
Allow to pass enablepullrequestautomergeinput.commitBody to the request

### ISSUE THREAD

**Issue by jurijzahn8019** [alexwilson/enable-github-automerge-action#200]
Hi there!

I woule like to have an input allowing to define `commitBody` for merge commit.

for example:

```yaml
uses: alexwilson/enable-github-automerge-action@1.0.0
with:
  github-token: "${{ secrets.GITHUB_TOKEN }}"
  merge-method: SQUASH
  commit-body: ${{ github.event.pull_request.body }}
```

or maybe as boolean, taking pr body automatically.

This will allow use case where commit must include contents of PR Body for further
Changelog automations on repos.

Corresponding docs: https://docs.github.com/en/graphql/reference/input-objects#enablepullrequestautomergeinput

Thanks :)
